import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from 'next/font/google'
import ApolloWrapper from './_lib/client';
import AppNavbar from './_components/Navbar';
import { cookies } from 'next/headers';
import { verifyToken } from '@/server/utils/auth';
import React from 'react';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const token = cookies().get('token')?.value;
  let payload = null;
  if (token) payload = await verifyToken(token);

  /* You're probably wondering why we can't use useContext here, it's because this is serverside, no hooks! */

  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <AppNavbar loggedIn={!!payload}/>
          { children }
        </ApolloWrapper>
      </body>
    </html>
  )
}